version: '3.8'

services:
  db-flask:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: p1_db_flask
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_flask_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5


  flask:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db-flask:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-flask:5432/p1_db_flask

volumes:
  db_flask_data: